"""empty message

Revision ID: 080adf011f52
Revises: 657e9d0de8b9
Create Date: 2022-02-11 16:45:35.633993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080adf011f52'
down_revision = '657e9d0de8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_book_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['books_author.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books_book.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'author_id')
    )
    op.create_index(op.f('ix_books_book_authors_author_id'), 'books_book_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_books_book_authors_book_id'), 'books_book_authors', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_book_authors_book_id'), table_name='books_book_authors')
    op.drop_index(op.f('ix_books_book_authors_author_id'), table_name='books_book_authors')
    op.drop_table('books_book_authors')
    # ### end Alembic commands ###
