"""empty message

Revision ID: 657e9d0de8b9
Revises: 
Create Date: 2022-02-11 16:44:36.809282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657e9d0de8b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('death_year', sa.SmallInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('gutenberg_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.CheckConstraint('download_count >= 0'),
    sa.CheckConstraint('gutenberg_id >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gutenberg_id')
    )
    op.create_table('books_bookshelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('books_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('books_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_subject')
    op.drop_table('books_language')
    op.drop_table('books_bookshelf')
    op.drop_table('books_book')
    op.drop_table('books_author')
    # ### end Alembic commands ###
