"""empty message

Revision ID: bd185a8266f9
Revises: 080adf011f52
Create Date: 2022-02-11 16:47:17.607567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd185a8266f9'
down_revision = '080adf011f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_book_bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('bookshelf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_book.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['bookshelf_id'], ['books_bookshelf.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'bookshelf_id')
    )
    op.create_index(op.f('ix_books_book_bookshelves_book_id'), 'books_book_bookshelves', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_book_bookshelves_bookshelf_id'), 'books_book_bookshelves', ['bookshelf_id'], unique=False)
    op.create_table('books_book_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_book.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['language_id'], ['books_language.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'language_id')
    )
    op.create_index(op.f('ix_books_book_languages_book_id'), 'books_book_languages', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_book_languages_language_id'), 'books_book_languages', ['language_id'], unique=False)
    op.create_table('books_book_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_book.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['books_subject.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'subject_id')
    )
    op.create_index(op.f('ix_books_book_subjects_book_id'), 'books_book_subjects', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_book_subjects_subject_id'), 'books_book_subjects', ['subject_id'], unique=False)
    op.create_table('books_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books_book.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_format_book_id'), 'books_format', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_format_book_id'), table_name='books_format')
    op.drop_table('books_format')
    op.drop_index(op.f('ix_books_book_subjects_subject_id'), table_name='books_book_subjects')
    op.drop_index(op.f('ix_books_book_subjects_book_id'), table_name='books_book_subjects')
    op.drop_table('books_book_subjects')
    op.drop_index(op.f('ix_books_book_languages_language_id'), table_name='books_book_languages')
    op.drop_index(op.f('ix_books_book_languages_book_id'), table_name='books_book_languages')
    op.drop_table('books_book_languages')
    op.drop_index(op.f('ix_books_book_bookshelves_bookshelf_id'), table_name='books_book_bookshelves')
    op.drop_index(op.f('ix_books_book_bookshelves_book_id'), table_name='books_book_bookshelves')
    op.drop_table('books_book_bookshelves')
    # ### end Alembic commands ###
